### ISSUE TITLE
r parameter not suitable to use as resource URI

### ISSUE THREAD

**Issue by seebi** [AKSW/article.ontowiki#20]
e.g. sometimes there is a short variant of the URI used

**Comment by seebi** [comment]
why not selectedResource here?

**Comment by k00ni** [comment]
Sometimes the users does not know, where he comes from and which resources was selected. Because of that we use the latest resource, located in the url. In my opinion, if you have the r parameter in the URL, the article component can be sure that the user really "mean" this selection. 

Is it possible that a given r parameter and selectedResource differs?

**Comment by seebi** [comment]
yes, r is not always an URI

**Comment by k00ni** [comment]
But if i click something which contains the r parameter, then this r will be my new selectedResource, am i right? Do we have to check if r is an valid URI? Or simply use selectedResource?

**Comment by seebi** [comment]
yes, simply use selectedResource (if this does not work, its a bug and should be fixed)

**Comment by k00ni** [comment]
b19bc393e6176f590d1bdb094d15867da8d13fb4 solves this issue.
